[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "full"
opacity = 0.85
blur = true
title = "Alacritty"

[font]
size = 14
offset = { x = 0, y = 1 }

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
unfocused_hollow = true

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5c2e7"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.selection]
text = "#1e1e2e"
background = "#cba6f7"

[bell]
animation = "EaseOutExpo"
duration = 150
color = "#313244"

[mouse]
hide_when_typing = true

[terminal]
shell = { program = "/home/codebarre/.cargo/bin/nu" }
