# généré par quickshell
theme[main_bg]="#1e1e2e"
theme[main_fg]="#cdd6f4"
theme[title]="#cdd6f4"
theme[hi_fg]="#89b4fa"
theme[selected_bg]="#45475a"
theme[selected_fg]="#89b4fa"
theme[inactive_fg]="#6c7086"
theme[graph_text]="#a6adc8"
theme[meter_bg]="#45475a"
theme[proc_misc]="#a6adc8"

theme[cpu_box]="#cba6f7"
theme[mem_box]="#a6e3a1"
theme[net_box]="#f38ba8"
theme[proc_box]="#89b4fa"
theme[div_line]="#6c7086"

theme[temp_start]="#a6e3a1"
theme[temp_mid]="#f9e2af"
theme[temp_end]="#f38ba8"

theme[cpu_start]="#94e2d5"
theme[cpu_mid]="#89b4fa"
theme[cpu_end]="#cba6f7"

theme[free_start]="#cba6f7"
theme[free_mid]="#89b4fa"
theme[free_end]="#94e2d5"

theme[cached_start]="#94e2d5"
theme[cached_mid]="#89b4fa"
theme[cached_end]="#cba6f7"

theme[available_start]="#f9e2af"
theme[available_mid]="#fab387"
theme[available_end]="#f38ba8"

theme[used_start]="#a6e3a1"
theme[used_mid]="#94e2d5"
theme[used_end]="#89b4fa"

theme[download_start]="#f9e2af"
theme[download_mid]="#fab387"
theme[download_end]="#f38ba8"

theme[upload_start]="#a6e3a1"
theme[upload_mid]="#94e2d5"
theme[upload_end]="#89b4fa"

theme[process_start]="#89b4fa"
theme[process_mid]="#cba6f7"
theme[process_end]="#f5c2e7"
