# Window
window_padding_width 10
background_opacity 0.70
background_blur 1
hide_window_decorations no
confirm_os_window_close 0

# Font
font_family JetBrainsMono Nerd Font Regular
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
font_size 14.0
modify_font cell_height 101%

# Cursor
cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

# Colors
include theme.conf

# Bell
visual_bell_duration 0.15

# Mouse
mouse_hide_wait 3.0
shell /usr/bin/zsh
